# Generated by Django 4.2.1 on 2023-05-28 13:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FaceRecognition', '0002_visitor_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedCustomerAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateField()),
                ('description', models.TextField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EngineerApprovedApp', to='FaceRecognition.manager')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerApprovedApp', to='FaceRecognition.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('app_link', models.TextField(blank=True, null=True)),
                ('app_date', models.DateField(blank=True, null=True)),
                ('app_time', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManagerApp', to='FaceRecognition.manager')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VisitorApp', to='FaceRecognition.visitor')),
            ],
        ),
    ]
