# Generated by Django 4.2.1 on 2023-05-31 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0002_visitor_manager'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedVisitorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateField()),
                ('description', models.TextField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManagerApprovedApp', to='FaceRecognition.manager')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VisitorApprovedApp', to='FaceRecognition.visitor')),
            ],
            options={
                'unique_together': {('visitor', 'manager', 'approval_date')},
            },
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='app_date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='app_link',
            new_name='appointment_link',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='app_time',
            new_name='appointment_time',
        ),
        migrations.DeleteModel(
            name='ApprovedCustomerAppointment',
        ),
    ]
