# Generated by Django 4.2.1 on 2023-06-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_approvedvisitorappointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_link',
        ),
    ]
