# Generated by Django 4.2.1 on 2023-06-18 05:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0003_remove_appointment_appointment_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='address', max_length=300)),
                ('city', models.CharField(default='city', max_length=100)),
                ('country', models.CharField(default='country', max_length=100)),
                ('postcode', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
