# Generated by Django 4.2.1 on 2023-05-28 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FaceRecognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pictures')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='address', max_length=300)),
                ('email_address', models.CharField(default='email', max_length=100)),
                ('city', models.CharField(default='city', max_length=100)),
                ('postcode', models.IntegerField(default=0)),
                ('country', models.CharField(default='country', max_length=100)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visitor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pictures')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('role', models.CharField(default='role', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='address', max_length=300)),
                ('email_address', models.CharField(default='email', max_length=100)),
                ('city', models.CharField(default='city', max_length=100)),
                ('postcode', models.IntegerField(default=0)),
                ('country', models.CharField(default='country', max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
