# Generated by Django 4.2.1 on 2023-06-11 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0002_visitor_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_total', models.IntegerField(default=0)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EngineerServiceField', to='FaceRecognition.manager')),
            ],
        ),
    ]
