# Generated by Django 4.2.1 on 2023-06-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0003_managerappointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
